#ifndef CONFIG_H
#define CONFIG_H

#define MRPTREE_PROJECT_NAME  "@CMAKE_PROJECT_NAME@"

#define MRPTREE_VERSION       "@MRPTree_VERSION@"
#define MRPTREE_VERSION_MAJOR @MRPTree_VERSION_MAJOR@
#define MRPTREE_VERSION_MINOR @MRPTree_VERSION_MINOR@
#define MRPTREE_VERSION_PATCH @MRPTree_VERSION_PATCH@
#define MRPTREE_VERSION_TWEAK @MRPTree_VERSION_TWEAK@
#define MRPTREE_VERSION_TAG   "v@MRPTree_VERSION@"
#define MRPTREE_VERSION_DATE  "@MRPTREE_VERSION_DATE@"

#define MRPTREE_FOUND_DOXYGEN @MRPTREE_FOUND_DOXYGEN@
#define MRPTREE_FOUND_BOOST   @MRPTREE_FOUND_BOOST@
#define MRPTREE_FOUND_MRASTER @MRPTREE_FOUND_MRASTER@

#endif
